name: Build and Release Electron App

on:
  workflow_dispatch:

jobs:
  build-electron:
    strategy:
      matrix:
        os: [macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      artifact-folder: release-artifacts

    steps:
      - name: Checkout Electron frontend
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download and prepare backend (macOS)
        if: matrix.os == 'macos-13'
        shell: bash
        run: |
          curl -L -o backend.zip https://github.com/logan-taggart/TRAIT-Back/releases/latest/download/backend-macintel.zip
          unzip backend.zip -d temp-backend
          rm -rf backend
          cp -r temp-backend/backend backend
          chmod +x backend/backend
          rm -rf backend.zip temp-backend

      - name: Download and prepare backend (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/logan-taggart/TRAIT-Back/releases/latest/download/backend-windows.zip" -OutFile "backend.zip"
          Expand-Archive -Path "backend.zip" -DestinationPath "temp-backend" -Force
          Remove-Item -Recurse -Force backend -ErrorAction SilentlyContinue
          Copy-Item -Path "temp-backend/backend" -Destination "backend" -Recurse -Force
          Remove-Item backend.zip
          Remove-Item -Recurse -Force temp-backend

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build-all

      - name: Create release artifacts folder
        run: mkdir -p release-artifacts

      - name: Zip Electron build (macOS)
        if: matrix.os == 'macos-13'
        run: zip -r release-artifacts/TRAIT-MacIntel.zip dist

      - name: Zip Electron build (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: Compress-Archive -Path dist\* -DestinationPath release-artifacts\TRAIT-Windows.zip

      - name: Upload release artifact folder
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release-zips
          path: release-artifacts

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-electron

    steps:
      - name: Download macOS build zip
        uses: actions/download-artifact@v4
        with:
          name: macos-13-release-zips
          path: release-artifacts

      - name: Download Windows build zip
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-release-zips
          path: release-artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.run_id }}
          tag_name: release-${{ github.run_id }}
          body: "Automated release for commit `${{ github.sha }}`"
          files: release-artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}